apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
  namespace: hospitals

spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: hospital-app

  template:
    metadata: 
      labels:
        app: hospital-app

    spec:
      containers:
      - name: hospital-app
        image: chandrashekar1530/hospital-app:v1.0.0

        ports:
        - containerPort: 3000
        envFrom:
        - name: hospital-config

        env:
        - name: DB_PASSWORD
          valueFrom:
            secretkeyRef:
              name: hospital-secret
              key: DB_PASSWORD
